import test from 'node:test';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
import {exercises,challengeDocument,challengeScore,validChallengeMessage} from '../src/lib/codeChallenge.mjs';
async function run(index,js,css=exercises[index].css){let output;const e=exercises[index];const d=new JSDOM(challengeDocument(e,{html:e.html,css,js},'unit-token',true),{runScripts:'dangerously',pretendToBeVisual:true,beforeParse(w){w.postMessage=data=>{output=data;};}});await new Promise(r=>setTimeout(r,90));d.window.close();return output;}
test('Each original starter fails a meaningful behavioral test',async()=>{for(let i=0;i<exercises.length;i++){const r=await run(i,exercises[i].js);assert.ok(validChallengeMessage(r,'unit-token'));assert.equal(challengeScore(r.results,false),0,exercises[i].title);}});
test('Menu correction passes open, close and accessible state checks',async()=>{const r=await run(0,'const b=document.querySelector("#menu-toggle"),m=document.querySelector("#menu");b.onclick=()=>{m.hidden=!m.hidden;b.setAttribute("aria-expanded",String(!m.hidden));};');assert.equal(r.results.length,5);assert.equal(challengeScore(r.results,false),100);assert.equal(challengeScore(r.results,true),75);});
test('Scheduling checks reject overlap and preserve adjacent appointments',async()=>{const r=await run(4,'window.isSlotAvailable=(start,end,slots)=>end>start&&!slots.some(s=>start<s.end&&end>s.start);');assert.equal(challengeScore(r.results,false),100);});
test('Queue checks distinguish parallel tasks from sequential execution',async()=>{const r=await run(5,'window.runQueue=async tasks=>{const result=[];for(const task of tasks)result.push(await task());return result;};');assert.equal(challengeScore(r.results,false),100);});
test('Messages require a matching token and a bounded typed result list',()=>{assert.equal(validChallengeMessage({type:'challenge-result',token:'bad',results:[]},'expected'),false);assert.equal(validChallengeMessage({type:'challenge-result',token:'ok',results:[{label:'test',pass:'true'}]},'ok'),false);assert.equal(validChallengeMessage({type:'challenge-result',token:'ok',results:Array(31).fill({label:'test',pass:true})},'ok'),false);});
test('Code stays within an opaque sandbox document and cannot close its runner script',()=>{const doc=challengeDocument(exercises[0],{html:exercises[0].html,css:'',js:'</script><script>parent.document.body.remove()</script>'},'token');assert.equal((doc.match(/<script>/g)||[]).length,1);assert.match(doc,/connect-src 'none'/);assert.match(doc,/form-action 'none'/);assert.match(doc,/\\u003c\/script>/);});

test("CSS checks parse RGB colors and accept sufficient contrast",async()=>{const r=await run(1,'document.querySelector("#action").getBoundingClientRect=()=>({height:44});','#action {background:#202020;color:#ffffff;min-height:44px;outline-width:3px;outline-style:solid;outline-color:#de8750;}');assert.equal(r.results.length,3);assert.equal(challengeScore(r.results,false),100);});

test("A keyboard-only focus rule is accepted after pointer-triggered verification",async()=>{const r=await run(1,'document.querySelector("#action").getBoundingClientRect=()=>({height:44});','#action {background:#202020;color:#ffffff;min-height:44px;outline:none;} #action:focus-visible {outline-width:3px;outline-style:solid;outline-color:#de8750;}');assert.equal(challengeScore(r.results,false),100);});
