'use client';
import {usePreferences,PreferenceControls} from './Preferences';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import {AnimatePresence,motion,useReducedMotion} from 'framer-motion';
import {validateRequest,bookingServices} from '@/lib/security.mjs';
import {profile} from '@/data/portfolio';
import {bookingSettings,dateKey,monthDays,shiftMonth,proposedTimes,formatDay,requestMailto,tentativeCalendar,bookingMessage} from '@/lib/booking.mjs';
import {MotionTitle,MotionCopy} from './MotionTitle';

export default function Booking(){
 const {localize,t,language}=usePreferences();
 const reduce=useReducedMotion();
 const [now,setNow]=useState<Date|null>(null),[month,setMonth]=useState(''),[day,setDay]=useState(''),[time,setTime]=useState('');
 const [request,setRequest]=useState<{day:string;time:string;name:string;email:string;service:string;message:string}|null>(null);
 const [notice,setNotice]=useState('');const formRef=useRef<HTMLFormElement>(null),resultRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{setNow(new Date());setMonth(dateKey(new Date()).slice(0,7));const timer=setInterval(()=>setNow(new Date()),60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(now&&time&&!proposedTimes(day,now).includes(time)){setTime('');setRequest(null);setNotice('Ce créneau est passé. Choisissez un autre horaire.');}},[now,day,time]);
 useEffect(()=>{if(request)resultRef.current?.focus();},[request]);
 useEffect(()=>{if(!time||!matchMedia('(max-width: 760px)').matches)return;const frame=requestAnimationFrame(()=>formRef.current?.closest('.booking-form-wrap')?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'start'}));return()=>cancelAnimationFrame(frame);},[time,reduce]);
 const minimum=now?dateKey(now).slice(0,7):'',maximum=minimum?shiftMonth(minimum,bookingSettings.horizonMonths):'';
 const calendar=month?monthDays(month):{offset:0,days:[]};const times=now&&day?proposedTimes(day,now):[];
 const selectDay=(value:string)=>{setDay(value);setTime('');setRequest(null);setNotice('');};
 const selectTime=(value:string)=>{setTime(value);setRequest(null);setNotice('');};
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!now||!proposedTimes(day,new Date()).includes(time)){setNotice('Choisissez un créneau à venir.');setTime('');return;}const data=new FormData(e.currentTarget);try{const fields=validateRequest(Object.fromEntries(data),bookingServices,3000);setNotice('');setRequest({day,time,...fields} as {day:string;time:string;name:string;email:string;service:string;message:string});}catch(error){setRequest(null);setNotice(error instanceof Error?error.message:'Vérifiez les informations du formulaire.');}}
 function download(calendar:boolean){if(!request)return;const blob=new Blob([calendar?tentativeCalendar(request,new Date(),language):bookingMessage(request,language)],{type:calendar?'text/calendar;charset=utf-8':'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=calendar?'rendez-vous-a-confirmer.ics':'demande-rendez-vous.txt';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice(calendar?'Proposition ajoutable à votre agenda. Elle reste à confirmer.':'Demande téléchargée. Elle n’a pas été envoyée.');}
 return localize(<section id="booking" className="booking panel section-pad" aria-labelledby="booking-title">
  <div className="booking-heading"><div><span className="eyebrow">PRENONS LE TEMPS D’ÉCHANGER</span><MotionTitle id="booking-title" lines={['/RENDEZ-VOUS']}/></div><span className="booking-duration">↗ 30 minutes · Sans engagement</span></div>
  <MotionCopy className="booking-intro" text="Un site, une application ou une identité visuelle ? Proposez un moment pour en parler ensemble."/>
  <div className="booking-notes"><span>Horaires de Lomé · UTC+0</span><span><i/>Créneaux proposés · confirmation nécessaire</span></div>
  <div className="booking-layout"><motion.div className="booking-calendar" initial={reduce?false:{opacity:0,y:22}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:reduce?0:.65,ease:[.22,1,.36,1]}}><div className="calendar-header"><h3 aria-live="polite">{month?new Intl.DateTimeFormat(language==='en'?'en-GB':'fr-FR',{month:'long',year:'numeric',timeZone:bookingSettings.timezone}).format(new Date(`${month}-01T12:00:00Z`)):'Chargement du calendrier…'}</h3><div><button type="button" aria-label="Mois précédent" disabled={!month||month<=minimum} onClick={()=>{setMonth(shiftMonth(month,-1));selectDay('');}}>‹</button><button type="button" aria-label="Mois suivant" disabled={!month||month>=maximum} onClick={()=>{setMonth(shiftMonth(month,1));selectDay('');}}>›</button></div></div>
   <div className="calendar-week" aria-hidden="true">{(language==='en'?['M','T','W','T','F','S','S']:['L','M','M','J','V','S','D']).map((label,i)=><span key={i}>{label}</span>)}</div>
   <motion.div key={month} className="calendar-days" role="group" aria-label="Choisir un jour" initial={reduce?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{duration:reduce?0:.32,ease:[.22,1,.36,1]}}>{Array.from({length:calendar.offset},(_,i)=><span key={`blank-${i}`} aria-hidden="true"/>)}{calendar.days.map((value:string)=>{const enabled=now&&proposedTimes(value,now).length>0;return <button type="button" key={value} disabled={!enabled} aria-label={formatDay(value,language)} aria-pressed={day===value} className={day===value?'selected':''} onClick={()=>selectDay(value)}><span>{Number(value.slice(-2))}</span>{enabled&&<i aria-hidden="true"/>}</button>;})}</motion.div><p className="calendar-caption">Les points indiquent les jours où proposer un appel. Aucun agenda externe n’est synchronisé.</p></motion.div>
   <div className="booking-selection"><AnimatePresence mode="wait" initial={false}><motion.div key={day||'empty'} initial={{opacity:0,y:reduce?0:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:reduce?0:-8}} transition={{duration:reduce?0:.22}}>{!day?<div className="booking-empty"><span aria-hidden="true">↗</span><h3>Quel jour vous convient ?</h3><p>Choisissez une date, puis un horaire.</p></div>:<><span className="eyebrow">01 / VOTRE CRÉNEAU</span><h3 className="selected-day" aria-live="polite">{formatDay(day,language)}</h3><div className="booking-times" role="group" aria-label="Choisir un horaire">{times.map((value:string)=><button type="button" key={value} aria-pressed={time===value} className={time===value?'selected':''} onClick={()=>selectTime(value)}>{value}</button>)}</div><p className="booking-time-note">30 minutes · Africa/Lome (UTC+0)</p></>}</motion.div></AnimatePresence></div></div>
  <AnimatePresence>{time&&<motion.div className="booking-form-wrap" key="form" initial={{opacity:0,y:reduce?0:16}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:reduce?0:.3}}><div className="booking-form-intro"><span className="eyebrow">02 / FAISONS CONNAISSANCE</span><h3>Parlons de votre idée.</h3><p>{formatDay(day,language)} à <b>{time}</b><br/>La demande attendra ma confirmation.</p></div><form ref={formRef} onSubmit={submit} onChange={()=>setRequest(null)}><div className="form-row"><label>Votre nom<input required name="name" autoComplete="name" maxLength={120} placeholder="Comment vous appelez-vous ?"/></label><label>Votre email<input required name="email" type="email" autoComplete="email" maxLength={180} placeholder="vous@exemple.com"/></label></div><label>Le sujet de notre échange<select name="service" defaultValue="Site ou application"><option>Site ou application</option><option>Identité visuelle</option><option>Interfaces & expérience</option><option>Communication visuelle</option><option>Autre projet</option></select></label><label>Quelques mots pour préparer l’appel<textarea required name="message" minLength={10} maxLength={3000} rows={3} placeholder="Votre idée, vos objectifs, vos questions…"/></label><button className="pill dark" type="submit">Préparer ma demande <span aria-hidden="true">↗</span></button></form></motion.div>}</AnimatePresence>
  {request&&<div className="booking-result" ref={resultRef} tabIndex={-1} role="region" aria-label="Demande préparée"><span className="eyebrow">03 / VOTRE DEMANDE EST PRÊTE</span><h3>Un premier échange, bientôt.</h3><p>Ouvrez votre messagerie puis envoyez la demande à Joackim. Le rendez-vous sera confirmé par retour d’email.</p><div className="booking-result-actions">{profile.email?<a className="pill dark" href={requestMailto(profile.email,request,language)}>Ouvrir ma messagerie ↗</a>:<button type="button" className="pill dark" onClick={()=>download(false)}>Télécharger ma demande ↗</button>}<button type="button" className="text-link" onClick={()=>download(true)}>Ajouter la proposition à mon agenda ↗</button></div><p className="booking-disclaimer">La préparation ou le téléchargement n’envoie aucun message et ne réserve pas le créneau.</p></div>}
  <p className="booking-status" role="status">{notice}</p>
 </section>);
}
