'use client';
import {usePreferences} from './Preferences';
import {useEffect,useRef,useState} from 'react';
import {exercises as originalExercises,challengeDocument,challengeScore,validChallengeMessage} from '@/lib/codeChallenge.mjs';
import {localizedExercises} from '@/lib/localization.mjs';
import {MotionTitle,MotionCopy} from './MotionTitle';
const runnerSource='/challenge-runner.html';
type Code={html:string;css:string;js:string};
type Result={label:string;pass:boolean};
const initial=(index:number):Code=>({html:originalExercises[index].html,css:originalExercises[index].css,js:originalExercises[index].js});
export default function CodeChallenge(){
 const {localize,language}=usePreferences();
 const [open,setOpen]=useState(false),[phase,setPhase]=useState('intro'),[index,setIndex]=useState(0),[code,setCode]=useState<Code>(initial(0)),[tab,setTab]=useState<keyof Code>('js'),[view,setView]=useState('preview'),[results,setResults]=useState<Result[]>([]),[hint,setHint]=useState(false),[seconds,setSeconds]=useState(0),[scores,setScores]=useState<number[]>([]),[busy,setBusy]=useState(false),[preview,setPreview]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),frame=useRef<HTMLIFrameElement>(null),token=useRef(''),timer=useRef<ReturnType<typeof setTimeout>|null>(null),started=useRef(0),testing=useRef(false);
 const exercises=localizedExercises(originalExercises,language);
 const exercise=exercises[index];
 const initialCode=(item:number):Code=>({html:exercises[item].html,css:exercises[item].css,js:exercises[item].js});
 useEffect(()=>{if(!open)return;const d=dialog.current;d?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{d?.close();document.body.style.overflow=overflow;};},[open]);
 useEffect(()=>{if(!open||phase!=='playing')return;const interval=setInterval(()=>setSeconds(Math.floor((Date.now()-started.current)/1000)),1000);return()=>clearInterval(interval);},[open,phase]);
 useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.origin!=='null'||event.source!==frame.current?.contentWindow||!validChallengeMessage(event.data,token.current))return;setResults(event.data.results);setBusy(false);if(timer.current)clearTimeout(timer.current);if(testing.current)setView('tests');};window.addEventListener('message',receive);return()=>{window.removeEventListener('message',receive);if(timer.current)clearTimeout(timer.current);};},[]);
 function run(value=code,verify=false,item=index){if(Object.values(value).some(part=>part.length>64000)){setResults([{label:'Limite : 64 000 caractères par langage.',pass:false}]);setView('tests');setBusy(false);return;}if(timer.current)clearTimeout(timer.current);token.current=crypto.randomUUID();testing.current=verify;setView('preview');setResults([]);setBusy(true);setPreview(challengeDocument(exercises[item],value,token.current,verify,language));timer.current=setTimeout(()=>{setBusy(false);setResults([{label:'Le code ne répond pas. Vérifiez vos boucles puis relancez.',pass:false}]);setView('tests');setPreview('');},5000);}
 function launch(){started.current=Date.now();setSeconds(0);setScores([]);setIndex(0);setCode(initialCode(0));setTab('js');setHint(false);setPhase('playing');setView('preview');run(initialCode(0),false,0);}
 function advance(){const next=[...scores,testing.current?challengeScore(results,hint):0];setScores(next);if(index===exercises.length-1){setPhase('result');setPreview('');if(timer.current)clearTimeout(timer.current);return;}const n=index+1;setIndex(n);setCode(initialCode(n));setTab(n===1?'css':'js');setHint(false);setView('preview');run(initialCode(n),false,n);}
 function close(){token.current='';testing.current=false;setOpen(false);setPreview('');setBusy(false);if(timer.current)clearTimeout(timer.current);}
 const solved=!busy&&testing.current&&results.length>0&&results.every(r=>r.pass);
 return localize(<><section id="challenge" className="challenge panel section-pad"><div className="challenge-top"><span className="eyebrow">/LE DÉFI · CODE & DESIGN</span><span className="challenge-time">6 missions · À votre rythme</span></div><MotionTitle className="challenge-title" lines={['LE SENS',<>DU <em>DÉTAIL.</em></>]}/><span className="challenge-orbit" aria-hidden="true">✳</span><div className="challenge-bottom"><MotionCopy delay={.12} text="Un menu capricieux. Une interface à réparer. Une logique à retrouver. Entrez dans l’atelier et faites fonctionner les détails."/><button className="pill light" onClick={()=>{setPhase('intro');setOpen(true);}}>Relever le défi ↗</button></div><div className="challenge-levels"><span><i>01</i>Observer</span><span><i>02</i>Réparer</span><span><i>03</i>Tester</span></div><div className="challenge-ghost" aria-hidden="true">&gt; interface.repair()<br/>[ ] chaque détail compte<br/>&gt; code + design = expérience</div></section>
 <dialog ref={dialog} className="code-game" aria-label="Atelier code et design" onCancel={close}><div className="game-shell"><header className="game-header"><span>JOACKIM DATE <b>/ L’ATELIER</b></span><button className="game-close" onClick={close} aria-label="Fermer le défi">Fermer ×</button></header>
 {phase==='intro'?<div className="game-intro"><span className="eyebrow">À VOUS DE JOUER</span><h2>Les détails font<br/><em>la différence.</em></h2><p>Six petits bugs, du code à modifier et un aperçu réel. Corrigez, testez et avancez à votre rythme. Un indice réduit le score de la mission à 75 points.</p><div className="mission-grid">{exercises.map((e,i)=><article key={e.title}><span>0{i+1} ↗</span><h3>{e.title}</h3><small>{e.level}</small></article>)}</div><button className="pill game-primary" onClick={launch}>Lancer le défi ↗</button><span className="game-local-note">Score local à cette partie · Aucun compte nécessaire</span></div>:phase==='result'?<div className="game-result"><span className="eyebrow">PARTIE TERMINÉE</span><h2>{scores.reduce((a,b)=>a+b,0)}<small>/600</small></h2><h3>Chaque détail compte.</h3><p>{scores.filter(s=>s>0).length} mission(s) réussie(s) sur 6 · {Math.floor(seconds/60)} min {seconds%60} s</p><ol>{exercises.map((e,i)=><li key={e.title}><span>{e.title}</span><b>{scores[i]} / 100</b></li>)}</ol><div><button className="pill game-primary" onClick={launch}>Rejouer ↗</button><button className="pill game-secondary" onClick={close}>Retour au portfolio</button></div></div>:<>
 <div className="game-progress"><ol aria-label="Progression des missions">{exercises.map((e,i)=><li key={e.title} className={i===index?'current':i<index?'done':''} aria-current={i===index?'step':undefined}><span>{i<index?(scores[i]>0?'✓':'–'):i+1}</span><b>{e.title}</b></li>)}</ol><span className="game-clock">{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')} <b>{scores.reduce((a,b)=>a+b,0)} pts</b></span></div>
 <div className="game-brief"><span className="eyebrow">MISSION 0{index+1} / {exercise.level}</span><h2>{exercise.title}</h2><p>{exercise.brief}</p></div>
 <div className="game-workspace"><div className="game-editor"><div className="game-tabs" role="group" aria-label="Langage du code">{(['html','css','js'] as const).map(t=><button key={t} aria-pressed={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='js'?'JavaScript':t.toUpperCase()}</button>)}</div><div className="code-input"><pre aria-hidden="true">{code[tab].split('\n').map((_,i)=>i+1).join('\n')}</pre><textarea aria-label={`Code ${tab==='js'?'JavaScript':tab.toUpperCase()}`} spellCheck={false} maxLength={64000} value={code[tab]} onChange={e=>{setCode({...code,[tab]:e.target.value});setResults([]);testing.current=false;}}/></div><div className="editor-actions"><button onClick={()=>{setCode(initialCode(index));setResults([]);run(initialCode(index));}}>Réinitialiser ↻</button><button onClick={()=>setHint(true)}>Un indice ?</button><button className="run-preview" onClick={()=>{setView('preview');run();}}>Exécuter ↗</button></div>{hint&&<p className="game-hint" role="status">{exercise.hint}<small>Mission limitée à 75 points.</small></p>}</div>
 <div className="game-output"><div className="game-tabs" role="group" aria-label="Vue du résultat"><button className={view==='preview'?'active':''} aria-pressed={view==='preview'} onClick={()=>setView('preview')}>Aperçu</button><button className={view==='tests'?'active':''} aria-pressed={view==='tests'} onClick={()=>setView('tests')}>Tests {results.length?`${results.filter(r=>r.pass).length}/${results.length}`:''}</button></div><iframe key={preview} ref={frame} title="Aperçu isolé de votre code" sandbox="allow-scripts" referrerPolicy="no-referrer" src={preview?`${runnerSource}#${token.current}`:undefined} onLoad={()=>{if(preview&&token.current)frame.current?.contentWindow?.postMessage({type:"challenge-run",token:token.current,document:preview},"*");}} className={view==='preview'?'':'preview-hidden'}/>{view==='tests'&&<div className="game-tests" aria-live="polite">{busy?<p>Tests en cours…</p>:results.length?results.map((r,i)=><p key={i} className={r.pass?'pass':'fail'}><span>{r.pass?'✓':'×'}</span>{r.label}</p>):<p>Cliquez sur « Vérifier » pour lancer les tests.</p>}</div>}</div></div>
 <div className="game-controls"><span role="status">{solved?'Bien joué. Tous les tests passent.':busy?'Exécution en cours…':'Modifiez le code, puis vérifiez votre solution.'}</span><div><button className="pill game-secondary" onClick={advance} disabled={busy}>{solved?(index===5?'Voir mon résultat ↗':'Mission suivante ↗'):'Passer la mission →'}</button><button className="pill game-primary" disabled={busy} onClick={()=>run(code,true)}>Vérifier ✓</button></div></div>
 </>}
 </div></dialog></>);
}
